### ISSUE TITLE
Missing access controls

### ISSUE THREAD

**Issue by holiman** [decentralMind/sign-the-doc#1]
Just browsed the code a bit, I might have missed something, but afaict the method `recordInitialDoc` is public, and anyone can set the data (`creatorAddress`, `date`,`signature` etc) on any/all documents. 

```
    creator.creatorAddress = msg.sender;
    creator.creationDate = block.timestamp;
    creator.expiryDate = expiryDate;
    creator.docHash = docHash;
    creator.signature = signature;
creator.authorisedSignerList = authorisedSignerList;
```

It almost looks like a `bugdoor`, for two reasons: 

- the `public` keyword is so far off to the right that it's almost clipped by the GH code pane, and for all other methods the modifiers are placed on separate lines, for visibility. 
- it is a separate method, despite the _only_ use of it comes from `createDocToSign`

**Comment by decentralMind** [comment]
Hi holiman, thank you for pointing out,  I set the method recordInitialDoc to internal function. I'm in process of refactoring the whole code. I apologies for looking into this issue late, I had to plan some other non coding project, I'm extremely glad and happy to be back at coding solidity.
